CREATE TABLE Animal (
    AnimalId INT PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(50) NOT NULL,
    Breed VARCHAR(50) NOT NULL,
    BirthDate DATE NOT NULL,
    Sex VARCHAR(6) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    Status VARCHAR(8) NOT NULL
);